#!/bin/bash

# Builds the specified image using the proper options.

# This is to turn off the fancy screen control for logging.
# It's pretty, but it prevents the user from seeing more than a few
# lines above the point of failure.
OPTS="--progress plain"

if (( $# < 3 )); then
    echo >&2 "Missing '-t name'."
    exit 1
fi

set -x
docker build $OPTS "$@" context
