#!/bin/bash

terminal=$(tty)
if (( $? > 0 )); then
    echo "No pseudoterminal allocated.  Failed."
    exit 1
else
    echo "Connected on $terminal as pid $$"
fi

LOGFILE=/tmp/mt-serve

exec >"$LOGFILE" 2>&1
echo "Command line: $0 $*"

source /home/maptool/.ssh/setup.sh

export
[[ "$REMOTE" == "" ]] && exit 1
echo -e "\nPlayer '$REMOTE' logged in at $(date)"

# Close stdout and stderr.  Not critical, but it ensures that space used by
# $LOGFILE can be freed by just removing the file.
exec /bin/sleep 3600 1>&- 2>&-
